/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinz.pure.http

import kotlinz.pure.http.controller.AuthorController
import kotlinz.pure.http.controller.BookController
import kotlinz.pure.http.database.*
import kotlinz.pure.http.http.HttpServerConfig
import kotlinz.pure.http.repositories.RepositoryExecutor

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    RepositoryExecutor.execute()
    AuthorController.createContexts(HttpServerConfig.server)
    BookController.createContexts(HttpServerConfig.server)
    HttpServerConfig.createHttpServer(8080)
}
