/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinz.pure.http

import kotlinz.pure.http.controller.AuthorController
import kotlinz.pure.http.controller.BookController
import kotlinz.pure.http.database.AuthorRepository
import kotlinz.pure.http.http.HttpServerConfig

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    AuthorRepository.createTable()
    AuthorController.createContexts(HttpServerConfig.server)
    BookController.createContexts(HttpServerConfig.server)
    HttpServerConfig.createHttpServer(8080)
}
